### ISSUE TITLE
Кодировка

### ISSUE THREAD

**Issue by coursar** [AlekseiILitvinov/HomeworkWebApp#3]
`<%@ page contentType="text/html;charset=UTF-8" language="java" %>` - надо добавить в каждую страницу, чтобы с русским всё было в порядке.

**Comment by AlekseiILitvinov** [comment]
К bootstrap-scc.jsp и bootstrap-scripts.jsp тоже нужно добавлять? Я думал, они подставляются в страницы catalog.jsp и error.jsp и принимают их настройки (там у меня проставлены настройки кодировки (как в видео).

**Comment by coursar** [comment]
Нет, к ним не надо, но надо было req.setCharacterEncoding("UTF-8")
